services:
#  Moving Average Scalper strategy
  kraken-trader-moving-average:
    image: kraken-trader:latest
    command: [ "movingAverageScalper", "DOGE/USD,XRP/USD,ETH/USD,HONEY/USD,PEPE/USD,FLR/USD,SGB/USD", "2000" ]
    volumes:
      - ./logs/movingAverageScalper:/app/logs

#  Multi Index Momentum strategy
  kraken-trader-multi-index:
    image: kraken-trader:latest
    command: [ "multiIndexMomentum", "DOGE/USD,XRP/USD,ETH/USD,HONEY/USD,PEPE/USD,FLR/USD,SGB/USD", "2000" ]
    volumes:
      - ./logs/multiIndexMomentum:/app/logs

#  Buy low sell high strategy
  kraken-trader-buy-low-sell-high:
    image: kraken-trader:latest
    command: [ "buyLowSellHighStrategy", "DOGE/USD,ETH/USD,HONEY/USD,PEPE/USD,FLR/USD,SGB/USD", "2000" ]
    environment:
      TZ: Europe/Zurich
    volumes:
      - ./logs/buyLowSellHighStrategy:/app/logs


  # StrategyOptimizationRunner
  strategy-optimizer:
    image: strategy-optimizer:latest
    environment:
      TZ: Europe/Zurich
    volumes:
      - ./logs/optimizer:/app/logs
      - ./data:/app/data
    command: [ "XDGUSD,ETHUSD,SOLUSD,XRPUSD,LTCUSD,FLRUSD,HONEYUSD,PEPEUSD,SGBUSD", "5" ]
