# Use Java 21 base image for the build process
FROM eclipse-temurin:21-jdk AS build

LABEL description="Build step using Java 21 for KrakenTraderApplication"

# Set working directory
WORKDIR /app

# Copy Gradle wrapper and project files
COPY gradlew /app/gradlew
COPY gradle /app/gradle
COPY build.gradle /app/build.gradle
COPY settings.gradle /app/settings.gradle
COPY src /app/src

# Grant execute permissions to Gradle wrapper
RUN chmod +x ./gradlew

# Build the application using Gradle
RUN ./gradlew bootJarTrader --no-daemon

# Final runtime image
FROM eclipse-temurin:21

LABEL description="Runtime image for KrakenTraderApplication" \
      name="krakentraderapplication" \
      tag="latest"

# Set working directory
WORKDIR /app

# Copy the JAR file from the build stage
COPY --from=build /app/build/libs/kraken-trader-*.jar /app/KrakenTraderApplication.jar

# Copy all model*.h5 files from local folder to the app folder
COPY model*.h5 /app/

# Set the entry point
ENTRYPOINT ["java", "-jar", "/app/KrakenTraderApplication.jar"]