spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  application:
    name: "kraken-trader"
  datasource:
    url: jdbc:h2:file:./data/db/kraken-trader;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
kraken:
  api:
    key: ${API_KEY}
    secret: ${API_SECRET}
logging:
  level:
    ch.kekelidze.krakentrader.indicator.AdxIndicator: INFO
    ch.kekelidze.krakentrader.indicator.MovingAverageIndicator: debug
    ch.kekelidze.krakentrader.indicator.SimpleMovingAverageDivergenceIndicator: debug
    ch.kekelidze.krakentrader.indicator.MovingAverageDivergenceCrossOverIndicator: info
    ch.kekelidze.krakentrader.indicator.MFIIndicator: info
    ch.kekelidze.krakentrader.indicator.PricePredictionIndicator: INFO
    ch.kekelidze.krakentrader.indicator.VolumeIndicator: debug
    ch.kekelidze.krakentrader.indicator.RsiIndicator: info
    ch.kekelidze.krakentrader.indicator.RsiRangeIndicator: debug
    ch.kekelidze.krakentrader.indicator.RiskManagementIndicator: debug
    ch.kekelidze.krakentrader.indicator.MovingTrendIndicator: info
    ch.kekelidze.krakentrader.indicator.VolatilityIndicator: debug

    ch.kekelidze.krakentrader.indicator.analyser.SupportResistanceAnalyser: info
    ch.kekelidze.krakentrader.indicator.analyser.VolatilityAnalyser: info
    ch.kekelidze.krakentrader.indicator.analyser.BollingerContractionAnalyser: info
    ch.kekelidze.krakentrader.indicator.analyser.TrendAnalyser: debug

    ch.kekelidze.krakentrader.strategy.PricePredictionStrategy: INFO
    ch.kekelidze.krakentrader.strategy.MovingAverageScalper: info
    ch.kekelidze.krakentrader.strategy.MultiIndexMomentumStrategy: info
    ch.kekelidze.krakentrader.strategy.MultiTimeFrameLowHighStrategy: info
    ch.kekelidze.krakentrader.strategy.ConsolidationStrategy: info
    ch.kekelidze.krakentrader.strategy.BuyLowSellHighStrategy: debug

    ch.kekelidze.krakentrader.optimize.GeneticOptimizer: info
    ch.kekelidze.krakentrader.optimize.MultiStrategyOptimizer: info

    ch.kekelidze.krakentrader.api.rest.service.KrakenAveragePriceService: info

    ch.kekelidze.krakentrader.backtester.service.BackTesterService: info
    ch.kekelidze.krakentrader.api.websocket.KrakenWebSocketClient: info
    ch.kekelidze.krakentrader.api.websocket.service.KrakenWebSocketService: debug

    ch.kekelidze.krakentrader.trade.service.TradeService: debug

  file:
    name: logs/kraken-trader.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss, Europe/Zurich} [%t] %-5level %logger{36} - %msg%n"