spring:
  application:
    name: "kraken-trader"
kraken:
  api:
    key: ABC
    secret: ABC
logging:
  level:
    ch.kekelidze.krakentrader.indicator.AdxIndicator: INFO
    ch.kekelidze.krakentrader.indicator.MovingAverageIndicator: DEBUG
    ch.kekelidze.krakentrader.indicator.MovingAverageDivergenceIndicator: DEBUG
    ch.kekelidze.krakentrader.indicator.MFIIndicator: debug
    ch.kekelidze.krakentrader.indicator.PricePredictionIndicator: INFO
    ch.kekelidze.krakentrader.indicator.VolumeIndicator: INFO
    ch.kekelidze.krakentrader.indicator.RsiIndicator: DEBUG
    ch.kekelidze.krakentrader.indicator.RiskManagementIndicator: INFO

    ch.kekelidze.krakentrader.strategy.WeightedAgreementStrategy: DEBUG
    ch.kekelidze.krakentrader.strategy.PricePredictionStrategy: INFO
    ch.kekelidze.krakentrader.strategy.MovingAverageScalper: DEBUG
    ch.kekelidze.krakentrader.strategy.MultiIndexMomentumStrategy: debug

    ch.kekelidze.krakentrader.api.service.KrakenAveragePriceService: debug

    ch.kekelidze.krakentrader.backtester.service.BackTesterService: INFO
    ch.kekelidze.krakentrader.api.KrakenWebSocketClient: debug

  file:
    name: logs/kraken-trader.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%t] %-5level %logger{36} - %msg%n"