spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  application:
    name: "kraken-trader"
kraken:
  api:
    key: ABC
    secret: ABC
logging:
  level:
    ch.kekelidze.krakentrader.indicator.AdxIndicator: INFO
    ch.kekelidze.krakentrader.indicator.MovingAverageIndicator: info
    ch.kekelidze.krakentrader.indicator.SimpleMovingAverageDivergenceIndicator: debug
    ch.kekelidze.krakentrader.indicator.MovingAverageDivergenceCrossOverIndicator: info
    ch.kekelidze.krakentrader.indicator.MFIIndicator: info
    ch.kekelidze.krakentrader.indicator.PricePredictionIndicator: INFO
    ch.kekelidze.krakentrader.indicator.VolumeIndicator: INFO
    ch.kekelidze.krakentrader.indicator.RsiIndicator: info
    ch.kekelidze.krakentrader.indicator.RiskManagementIndicator: info
    ch.kekelidze.krakentrader.indicator.MovingTrendIndicator: info

    ch.kekelidze.krakentrader.indicator.analyser.SupportResistanceAnalyser: info
    ch.kekelidze.krakentrader.indicator.analyser.VolatilityAnalyser: info
    ch.kekelidze.krakentrader.indicator.analyser.BollingerContractionAnalyser: info

    ch.kekelidze.krakentrader.strategy.PricePredictionStrategy: INFO
    ch.kekelidze.krakentrader.strategy.MovingAverageScalper: info
    ch.kekelidze.krakentrader.strategy.MultiIndexMomentumStrategy: info
    ch.kekelidze.krakentrader.strategy.MultiTimeFrameLowHighStrategy: debug
    ch.kekelidze.krakentrader.strategy.ConsolidationStrategy: info
    ch.kekelidze.krakentrader.strategy.BuyLowSellHighStrategy: info

    ch.kekelidze.krakentrader.optimize.GeneticOptimizer: debug
    ch.kekelidze.krakentrader.optimize.MultiStrategyOptimizer: debug

    ch.kekelidze.krakentrader.api.rest.service.KrakenAveragePriceService: debug

    ch.kekelidze.krakentrader.backtester.service.BackTesterService: info
    ch.kekelidze.krakentrader.api.websocket.KrakenWebSocketClient: debug

  file:
    name: logs/kraken-trader.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%t] %-5level %logger{36} - %msg%n"