spring:
  application:
    name: "kraken-trader"
kraken:
  api:
    key: ABC
    secret: ABC
logging:
  level:
    ch.kekelidze.krakentrader.indicator.AdxIndicator: INFO
    ch.kekelidze.krakentrader.indicator.MovingAverageIndicator: DEBUG
    ch.kekelidze.krakentrader.indicator.SimpleMovingAverageDivergenceIndicator: info
    ch.kekelidze.krakentrader.indicator.MovingAverageDivergenceCrossOverIndicator: info
    ch.kekelidze.krakentrader.indicator.MFIIndicator: info
    ch.kekelidze.krakentrader.indicator.PricePredictionIndicator: INFO
    ch.kekelidze.krakentrader.indicator.VolumeIndicator: INFO
    ch.kekelidze.krakentrader.indicator.RsiIndicator: info
    ch.kekelidze.krakentrader.indicator.RiskManagementIndicator: INFO

    ch.kekelidze.krakentrader.indicator.analyser.SupportResistanceAnalyser: debug
    ch.kekelidze.krakentrader.indicator.analyser.VolatilityAnalyzer: info

    ch.kekelidze.krakentrader.strategy.WeightedAgreementStrategy: DEBUG
    ch.kekelidze.krakentrader.strategy.PricePredictionStrategy: INFO
    ch.kekelidze.krakentrader.strategy.MovingAverageScalper: DEBUG
    ch.kekelidze.krakentrader.strategy.MultiIndexMomentumStrategy: info
    ch.kekelidze.krakentrader.strategy.MultiTimeFrameLowHighStrategy: debug
    ch.kekelidze.krakentrader.strategy.ConsolidationStrategy: debug

    ch.kekelidze.krakentrader.api.rest.service.KrakenAveragePriceService: debug

    ch.kekelidze.krakentrader.backtester.service.BackTesterService: debug
    ch.kekelidze.krakentrader.api.websocket.KrakenWebSocketClient: debug

  file:
    name: logs/kraken-trader.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%t] %-5level %logger{36} - %msg%n"